# Generated by Django 3.2.5 on 2021-07-23 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210722_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_following',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 3, 1, 7, 184205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 3, 1, 7, 184205, tzinfo=utc)),
        ),
    ]
