# Generated by Django 3.2.5 on 2021-07-23 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210723_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prewholeyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('tavg', models.FloatField(blank=True, null=True)),
                ('tmin', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preWholeYear',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 3, 15, 3, 994244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 3, 15, 3, 994244, tzinfo=utc)),
        ),
    ]
