# Generated by Django 3.2.5 on 2021-07-23 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210723_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank5',
            fields=[
                ('name', models.CharField(db_collation='utf8_bin', max_length=128, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'rank5',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 4, 15, 32, 981878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 4, 15, 32, 981878, tzinfo=utc)),
        ),
    ]
