# Generated by Django 3.2.5 on 2021-07-23 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210723_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxmin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('tmax', models.IntegerField(blank=True, null=True)),
                ('tmin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maxmin(1)',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 4, 28, 47, 716062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 4, 28, 47, 716062, tzinfo=utc)),
        ),
    ]
