# Generated by Django 3.2.5 on 2021-07-23 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210723_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maxmin1',
        ),
        migrations.AlterModelOptions(
            name='prewholeyear',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 7, 31, 23, 839944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 7, 31, 23, 839944, tzinfo=utc)),
        ),
    ]
