# Generated by Django 3.2.5 on 2021-07-24 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210723_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prewholeyear',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AlterField(
            model_name='prewholeyear',
            name='date',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 3, 17, 27, 35128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 3, 17, 27, 35128, tzinfo=utc)),
        ),
    ]
