# Generated by Django 3.2.5 on 2021-07-24 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210724_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 3, 20, 35, 124994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 3, 20, 35, 124994, tzinfo=utc)),
        ),
    ]
